/*
 * PyMOL native-core — Phase 1 FFI seam.
 *
 * NativeParseFloat() is the single call-site replacement for the pervasive
 *   sscanf(cc, "%f", &x) == 1
 * pattern in the coordinate parsers. It is a drop-in with identical semantics.
 *
 * When PYMOL_NATIVE_CORE is defined the call dispatches to the Rust
 * implementation (native-core crate) through the cxx bridge; otherwise it falls
 * back to the original sscanf so the build always works with the flag off.
 *
 * This header is the ONLY place C++ needs to know which backend is active.
 */

#pragma once

#include <cstdio>

#ifdef PYMOL_NATIVE_CORE
#include <cstddef>
#include <cstdint>
#include <cstring>

// Generated by corrosion_add_cxxbridge (or the cxxbridge CLI) from
// native-core/src/lib.rs. See CMakeLists.txt / native-core/README.md.
#include "native_core/src/lib.rs.h"

/**
 * Parse a leading float token from NUL-terminated `s`, mimicking
 * `sscanf(s, "%f", out) == 1`. Returns true and writes `*out` on success.
 */
inline bool NativeParseFloat(const char* s, float* out)
{
  return pymol_native::parse_f32(
      rust::Slice<const std::uint8_t>(
          reinterpret_cast<const std::uint8_t*>(s), std::strlen(s)),
      *out);
}

#else // !PYMOL_NATIVE_CORE

/** Fallback: the exact expression this seam replaces. */
inline bool NativeParseFloat(const char* s, float* out)
{
  return std::sscanf(s, "%f", out) == 1;
}

#endif // PYMOL_NATIVE_CORE
